"""add cellphone to user

Revision ID: 3d3619041ba9
Revises: 087bbf1bb6af
Create Date: 2025-12-14 15:14:26.359149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3619041ba9'
down_revision: Union[str, Sequence[str], None] = '087bbf1bb6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cellphone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cellphone')
    # ### end Alembic commands ###
